
// File {
//     _events: [Object: null prototype] {},
//     _eventsCount: 0,
//     _maxListeners: undefined,
//     size: 131540,
//     path:
//      'public\\uploads\\upload_b0347bb1ac49180325b54f214e65417d.jpg',
//     name: 'image (86).jpg',
//     type: 'image/jpeg',
//     hash: null,
//     lastModifiedDate: 2019-12-21T10:36:20.579Z,
//     _writeStream:
//      WriteStream {
//        _writableState:
//         WritableState {
//           objectMode: false,
//           highWaterMark: 16384,
//           finalCalled: true,
//           needDrain: false,
//           ending: true,
//           ended: true,
//           finished: true,
//           destroyed: true,
//           decodeStrings: true,
//           defaultEncoding: 'utf8',
//           length: 0,
//           writing: false,
//           corked: 0,
//           sync: false,
//           bufferProcessing: false,
//           onwrite: [Function: bound onwrite],
//           writecb: null,
//           writelen: 0,
//           bufferedRequest: null,
//           lastBufferedRequest: null,
//           pendingcb: 0,
//           prefinished: true,
//           errorEmitted: false,
//           emitClose: false,
//           autoDestroy: false,
//           bufferedRequestCount: 0,
//           corkedRequestsFree: [Object] },
//        writable: false,
//        _events: [Object: null prototype] {},
//        _eventsCount: 0,
//        _maxListeners: undefined,
//        path:
//         'public\\uploads\\upload_b0347bb1ac49180325b54f214e65417d.jpg',
//        fd: null,
//        flags: 'w',
//        mode: 438,
//        start: undefined,
//        autoClose: true,
//        pos: undefined,
//        bytesWritten: 131540,
//        closed: false } }